### ISSUE TITLE
Proposal new logo for WebRadio

### ISSUE THREAD

**Issue by rezamusic881** [Starcommander/StreamRadio#4]
Hi admin, I want to offer a new logo design is more sweet and simple application for WebRadio If you like and can accept it.

You can simply reply to this proposal, I will gladly send you a new logo this file and I was able to provide some variation for this app, thank you!

![webradioooo](https://user-images.githubusercontent.com/37515077/41175956-fc91be84-6b88-11e8-9f57-221d92144d31.png)

**Comment by alltagshack** [comment]
Hi. I build a fork with a complete, simple new design. A small logo update is added, too.

Hallo Starcommander! Du kannst ja mal in meine "geschwedete" (aus dem Film "Abgedreht") Version deiner App reinschauen. In der Regel lege ich für f-droid einen Metadata ordner an, der dann von f-droid automatisch eingeladen wird. Auch ist mein .gitignore eine feine Sache. Was mir nicht gelungen ist, dass ist der add-Dialog. Der ist ganz schmal geworden. Ich hab die Icons angepasst auf eine feste breite und viele weggeworfen... ich glaube die kleinen größen sind bei API 19 nicht mehr nötig.

Ich mag deine App und bin froh, dass sie FOSS ist. Weiter so! :-)

**Comment by Starcommander** [comment]
Nice!
I will have a closer look at your fork-project as soon I have the time.
Maybe it is a good idea to update StreamRadio with some of your changes?
Schöne Grüße aus Österreich ;)

**Comment by alltagshack** [comment]
Hi. There are some aspects I have to check (if I found time):

- I found a "Notification" Code... but I never see a notification
- check compatibility with (via emulator) android 4.4 or 4.2
- add/edit dialog is undersized

After checking/fixing it, I did a 2nd fork, modifying it again (in a minimalism way), and finally I try a merge-request with your code/repository. Actually I changed the app signature and package name to run both apps parallel. Feel free to adopt may changes. Alternatively you can wait for my merge request in the future. ;-)

Viele Grüße vom Niederrhein

**Comment by alltagshack** [comment]
Ok. fixed:

- on targetSdkVersion >= 26 the code needs a notification channel. I add it, now.
- I set minSdkVersion to 16 (Android 4.1) and test it on a real old phone (Android 4.2)
- add/edit dialog is shown as fullscreen, again. On Android 4.2 it still was fullscreen, on 8.1 it was terrible minimized

You may test the apk in my fork and give me a feedback. ;-)

**Comment by Starcommander** [comment]
Hello @no-go 
I tried your apk, and it looks nice.
Android 7.1.2 (LineageOS)
Thanks for your effort, good work!

**Some ideas that we could implement next:**

Single instance, so that WebRadio does not overlay the mainframe twice.
- We should try it with the launchMode in activity of AndroidManifest.xml
- android:launchMode="singleTask"
- I used this mode successful in PocketMaps app.

Better feedback about player is busy.
- As long as the label shows the name of the channel instead of "WebStreamPlayer", the player is busy.
- Maybe it is a better feedback for user, when a progressbar is moving forth and back while player busy.

Maybe user should be able to select between day- and nightmode, use it timebased, or use the sensor?
And of course, I will also update default channel list again.

**Comment by alltagshack** [comment]
Hi @Starcommander 
You are right. I think it is better to add a "black mode" checkbox to the options menu instead of the automatic (time based) night mode. I will try to copy this from another app of mine.

I will try to add and test the "singleTask" mode.

I although think, that a processbar is a good choice. I will try to add it. I have a additional question: I found different App names and labelings: WebRadio, StreamRadio and WebStreamRadio. Why? I think the labeling should be "WebRadio" all the time (?)

In another app of mine I add control buttons to a notification. I think it is not to hard to add a single, toggling "play/pause" button.

Hm. I think it is easyier for me not to make a new "clean" fork. So we have to see how we can get it back into your repository in the future :-P

**Comment by Starcommander** [comment]
@no-go 
Yes I agree, WebRadio should be used all times.
You should now be able to check in directly into Repository of WebRadio.
(Invitation sent)
As long as you do not create a new release - feel free to check in some changes directly.

**Comment by alltagshack** [comment]
:o)

**Comment by alltagshack** [comment]
Hi. I think my "merge" was really successful. The only open point is: play/pause actions into the notifications. I am struggeling at that point, because it will be a too big untested code part.

Test and compile it and enjoy. Maybe do a new clone on your system, because I remvoe and "gitignore" some unimportant folders from intellij/anroid studio.

**Comment by alltagshack** [comment]
logo and design is "fixed" since https://github.com/Starcommander/StreamRadio/commit/7955484e4d7a2e81d21ec23841b4dc9182435614

additionaly the logo above is far away from the classic one, is'n it?  :o)
